sudo: true
language: node_js
node_js:
- "iojs"
- '8'
addons:
  ssh_known_hosts: 159.65.226.145
before_install:
- '[ "${TRAVIS_NODE_VERSION}" != "0.8" ] || npm install -g npm@1.4.28'
- npm install -g npm@latest
- openssl aes-256-cbc -K $encrypted_a8c9b2db4a8b_key -iv $encrypted_a8c9b2db4a8b_iv
  -in rsa_travis.enc -out /tmp/rsa_travis -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/rsa_travis
- ssh-add /tmp/rsa_travis
deploy:
  provider: script
  skip_cleanup: true
  script: sh deploy.sh
  on:
    branch: master
