language: node_js
node_js:
- '8'
- '7'
- '6'
addons:
  ssh_known_hosts: 159.65.226.145
install: npm install
before_script: cd server
before_install:
- openssl aes-256-cbc -K $encrypted_a8c9b2db4a8b_key -iv $encrypted_a8c9b2db4a8b_iv
  -in rsa_deploy.enc -out /tmp/rsa_deploy -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/rsa_deploy
- ssh-add /tmp/rsa_deploy
deploy: 
    provider: script
    skip_cleanup: true
    script: sh deploy.sh
    on:
       branch: master
